#!/usr/bin/env bash
set -euo pipefail

INSTALL_PATH="${INSTALL_PATH:-/video52000/app}"
VIDEO_STORAGE_ROOT="${VIDEO_STORAGE_ROOT:-/video52000/videos}"
PORT="${PORT:-52000}"
NODE_ROLES="${NODE_ROLES:-sync,storage}"
NODE_TOKEN="${NODE_TOKEN:-}"

if [[ -z "$NODE_TOKEN" ]]; then
  echo "NODE_TOKEN is required. Use the token generated by the main app installer." >&2
  exit 1
fi

if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1; then
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update
    apt-get install -y ca-certificates curl gnupg
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
    apt-get install -y nodejs
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y nodejs npm
  elif command -v yum >/dev/null 2>&1; then
    curl -fsSL https://rpm.nodesource.com/setup_22.x | bash -
    yum install -y nodejs
  else
    echo "node and npm are required, and this OS is not supported for automatic install." >&2
    exit 1
  fi
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

mkdir -p "$INSTALL_PATH" "$VIDEO_STORAGE_ROOT"
cp "$PROJECT_ROOT/sync-node/server.js" "$INSTALL_PATH/server.js"
cp "$PROJECT_ROOT/sync-node/package.json" "$INSTALL_PATH/package.json"
cat > "$INSTALL_PATH/.env" <<EOF
PORT=$PORT
NODE_TOKEN=$NODE_TOKEN
NODE_ROLES=$NODE_ROLES
VIDEO_STORAGE_ROOT=$VIDEO_STORAGE_ROOT
EOF
chmod 600 "$INSTALL_PATH/.env"

cd "$INSTALL_PATH"
npm_config_cache=/tmp/npm-cache npm install --omit=dev

if command -v systemctl >/dev/null 2>&1 && [[ "$(id -u)" -eq 0 ]]; then
  cat > /etc/systemd/system/video52000-node.service <<EOF
[Unit]
Description=Video52000 sync/storage node
After=network.target

[Service]
Type=simple
WorkingDirectory=$INSTALL_PATH
EnvironmentFile=$INSTALL_PATH/.env
ExecStart=/usr/bin/env node $INSTALL_PATH/server.js
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable video52000-node.service
  systemctl restart video52000-node.service
  systemctl status video52000-node.service --no-pager
else
  if [[ -f /video52000/node.pid ]]; then
    kill "$(cat /video52000/node.pid)" >/dev/null 2>&1 || true
  fi
  nohup /usr/bin/env node "$INSTALL_PATH/server.js" >> /video52000/node.log 2>&1 &
  echo $! > /video52000/node.pid
  echo "Started with nohup, pid $(cat /video52000/node.pid)"
fi

for _ in $(seq 1 20); do
  if node -e "require('http').get('http://127.0.0.1:$PORT/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"; then
    echo "Node health check passed on 127.0.0.1:$PORT"
    exit 0
  fi
  sleep 1
done

echo "Node health check failed on 127.0.0.1:$PORT" >&2
exit 1
